### ISSUE TITLE
Incorrect Detectron2 Dependency

### ISSUE THREAD

**Issue by yizhe-ang** [ubc-vision/segmentation-sg#3]
I've installed `detectron2 == 0.2.1` as per the requirements stated in `INSTALL.md`.

However, I encountered errors such as `ImportError: cannot import name 'MaskRCNNConvUpsampleHead' from 'detectron2.modeling.roi_heads'` and `TypeError: AugInput() takes no arguments`.

Were you perhaps using a modified / different version of detectron2 that is not among the official releases?

**Comment by siddheshk** [comment]
Sorry about that. The version we built from source was slightly different from the officially released one. I've updated the version requirements in `INSTALL.md`. Please use `detectron==0.3` to resolve the issue.
