### ISSUE TITLE
FileNotFoundError test_coco_ids.pkl

### ISSUE THREAD

**Issue by techsho256** [ubc-vision/segmentation-sg#6]
It's good research and I'd like to use it too.

I'm following [this issue ](https://github.com/ubc-vision/segmentation-sg/issues/4) and fixing things.
I would like to run "pretrain_object_detector_withcoco.py", but  but I get an error.

```
FileNotFoundError: [Errno 2] No such file or directory: '/segmentationsg/coco/anotations/instances_train2017_clipped.json
```

I'm wondering if I can create instances_train2017_clipped.json by running `remove_intersection.py`.

So, when I run this file, I get this error next.

```
FileNotFoundError: [Errno 2] No such file or directory: /segmentationsg/scripts/test_coco_ids.pkl'
```

Please let me know how to solve this problem.

**Comment by siddheshk** [comment]
Sorry about that. The `instances_train2017_clipped` was just used for some ablation studies. You can replace it with `instances_train2017.json` instead as that is the original file from MSCOCO. I've made an update to the code.

**Comment by techsho256** [comment]
Thanks for committing to this.
I'll try the new version.
